# PPO algorithm configuration

algorithm:
  name: ppo
  clip_epsilon: 0.2
  value_coef: 0.5
  entropy_coef: 0.01
  num_epochs: 4
  gae_lambda: 0.95
  gamma: 0.99
  max_grad_norm: 0.5

training:
  learning_rate: 0.0003
  batch_size: 64
  minibatch_size: 8

optimizer:
  type: adam
  eps: 1e-5

scheduler:
  type: linear
  warmup_steps: 0
