# Rejection sampling algorithm configuration

algorithm:
  name: rejection_sampling
  reward_threshold: 0.8
  min_trajectories: 10

training:
  learning_rate: 0.0001
  num_epochs: 3
  batch_size: 16

optimizer:
  type: adamw
  weight_decay: 0.01

scheduler:
  type: cosine
  warmup_steps: 100
