# deploy-proxy.yaml

# 1. The Service Account the proxy will use
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-sa

---
# 2. The Permissions (Role) it needs
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list"]

---
# 3. Binding the Role to the Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
subjects:
- kind: ServiceAccount
  name: proxy-sa
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---
# 4. The Proxy Deployment itself
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      serviceAccountName: proxy-sa
      containers:
      - name: proxy
        image: europe-north2-docker.pkg.dev/my-project-1726641910410/ui-verifiers/proxy:latest
        ports:
        - containerPort: 8000

---
# 5. The Service to expose the proxy publicly
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  type: LoadBalancer # Asks the cloud provider for a public IP
  selector:
    app: proxy
  ports:
  - protocol: TCP
    port: 8000 # The port the public sees
    targetPort: 8000 # The port on the proxy container